# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# SEO settings
title:            "lvqin's blog"
description:      "This is a personal blog of Mingdong on Github Pages."
url:              https://lvqin614.github.io
enforce_ssl:      lvqin614.github.io

repo:             https://lvqin614/github.io
disqus_name:      "lvqin"
disqus_site_name: "lvqin's Blog"

# Author settings
author:
  name:       "lvqin"
  first_name: "lvqin"
  url:        https://mdluo.github.io
  github:     https://github.com/lvqin614
  twitter:    
  medium:     
  zhihu:      
  v2ex:       

# Build settings
permalink:    /blog/:title/
markdown:     kramdown
highlighter:  rouge

sass:
  style: compressed

paginate:       10
paginate_path:  /blog/page/:num/

gems:     ["jekyll-paginate"]

exclude:  ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
