# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# SEO settings
title:            "isilentfather's blog"
description:      "This is a personal blog of isilentfather on Github Pages."
url:              https://github.com/isilentfather
enforce_ssl:      isilentfather.github.io

repo:             https://github.com/isilentfather
disqus_name:      "isilentfather"
disqus_site_name: "isilentfather's Blog"

# Author settings
author:
  name:       "eyh"
  first_name: "eyh"
  url:        https://github.com/isilentfather
  github:     https://github.com/isilentfather
  twitter:    
  medium:     
  zhihu:      
  v2ex:       

# Build settings
permalink:    /blog/:title/
markdown:     kramdown
highlighter:  rouge

sass:
  style: compressed

paginate:       10
paginate_path:  /blog/page/:num/

gems:     ["jekyll-paginate"]

exclude:  ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
