# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# SEO settings
title:            "Mingdong's blog"
description:      "This is a personal blog of Mingdong on Github Pages."
url:              https://mdluo.github.io
enforce_ssl:      mdluo.github.io

repo:             https://github.com/mdluo/mdluo.github.io
disqus_name:      "mdluo"
disqus_site_name: "Mingdong's Blog"

# Author settings
author:
  name:       "Mingdong Luo"
  first_name: "Mingdong"
  url:        https://mdluo.github.io
  github:     https://github.com/mdluo
  twitter:    https://twitter.com/mdluo
  medium:     https://medium.com/@mdluo
  zhihu:      https://www.zhihu.com/people/mdluo
  v2ex:       https://www.v2ex.com/member/mdluo

# Build settings
permalink:    /blog/:title/
markdown:     kramdown
highlighter:  rouge

sass:
  style: compressed

paginate:       10
paginate_path:  /blog/page/:num/

gems:     ["jekyll-paginate"]

exclude:  ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
