# Site settings
title: Mingdong's blog
email: mingdong.luo@sap.com
description: > # this means to ignore newlines until "baseurl:"
  This is a personal blog of Mingdong on Github Pages.
  Read more in the About page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mdluo.github.io" # the base hostname & protocol for your site
twitter_username: mdluo
github_username:  mdluo

# Build settings
markdown: kramdown